copyright: Copyright &copy; 2023 Phillip Remmert
edit_uri: blob/main/docs/
remote_branch: gh-deploy
repo_name: pireba/testwiki.premmert.de
repo_url: https://github.com/pireba/testwiki.premmert.de
site_author: Phillip Remmert
site_name: Test Wiki | PRemmert
site_url: https://testwiki.premmert.de/
strict: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pireba
      name: GitHub

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

plugins:
  - search
  - glightbox:
      draggable: false
      effect: none

theme:
  favicon: assets/favicon.ico
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font: false
  icon:
    repo: fontawesome/brands/github
  language: en
  locale: en
  logo: assets/logo_white.png
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to Light Mode

